In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"E:\ML\CAR DETAILS.csv")
df

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [3]:
df.head(5)

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [4]:
df.describe()

year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [8]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['name']=encoder.fit_transform(df['name'])
df['year']=encoder.fit_transform(df['year'])
df['fuel']=encoder.fit_transform(df['fuel'])
df['seller_type']=encoder.fit_transform(df['seller_type'])
df['transmission']=encoder.fit_transform(df['transmission'])
df['owner']=encoder.fit_transform(df['owner'])
df

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0      775    13          60000      70000     4            1             1   
1     1041    13         135000      50000     4            1             1   
2      505    18         600000     100000     1            1             1   
3      118    23         250000      46000     4            1             1   
4      279    20         450000     141000     1            1             1   
...    ...   ...            ...        ...   ...          ...           ...   
4335   602    20         409999      80000     1            1             1   
4336   601    20         409999      80000     1            1             1   
4337   777    15         110000      83000     4            1             1   
4338   381    22         865000      90000     1            1             1   
4339  1154    22         225000      40000     4            1             1   

      owner  
0         0  
1         0  
2         0  
3         0  
4         2  
...     ...  
4335      2  
4336      2  
4337      2  
4338      0  
4339      0  

[4340 rows x 8 columns]

In [15]:
x=df.loc[:,df.columns!='selling_price']
y=df.iloc[:,2].values
x

name  year  km_driven  fuel  seller_type  transmission  owner
0      775    13      70000     4            1             1      0
1     1041    13      50000     4            1             1      0
2      505    18     100000     1            1             1      0
3      118    23      46000     4            1             1      0
4      279    20     141000     1            1             1      2
...    ...   ...        ...   ...          ...           ...    ...
4335   602    20      80000     1            1             1      2
4336   601    20      80000     1            1             1      2
4337   777    15      83000     4            1             1      2
4338   381    22      90000     1            1             1      0
4339  1154    22      40000     4            1             1      0

[4340 rows x 7 columns]

In [16]:
y

array([ 60000, 135000, 600000, ..., 110000, 865000, 225000], dtype=int64)

In [17]:
x=df.loc[:,df.columns!='selling_price']
y=df.iloc[:,2].values

name  year  km_driven  fuel  seller_type  transmission  owner
159     65    21     175000     1            1             1      0
4334  1418    18     170000     1            1             1      0
1657   898    12     110000     4            1             1      0
2188   326    21      66521     4            2             1      0
581     58    22      41000     4            0             1      0
...    ...   ...        ...   ...          ...           ...    ...
1033    13    19      58500     1            0             0      0
3264    51    18     110000     1            1             1      0
1653   116    22      22000     4            1             1      0
2607  1456    21      70000     1            1             1      0
2732  1048    19      62000     4            1             1      2

[3472 rows x 7 columns]

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [18]:
x_test

name  year  km_driven  fuel  seller_type  transmission  owner
2089   527    18      70070     1            0             0      0
1077     6    19      86000     1            0             0      0
1495   922    20     120000     4            1             1      4
555     39    25      30000     1            0             0      0
2615   124    15      95000     1            1             1      2
...    ...   ...        ...   ...          ...           ...    ...
1359   816    14     102000     4            0             1      0
4197   973    16     120000     1            1             1      4
1818   793    19      42000     4            1             1      4
2644   894    11      60000     4            1             1      4
917   1079    24      10000     1            0             0      0

[868 rows x 7 columns]

In [19]:
y_train

array([300000, 600000,  95000, ..., 270000, 600000, 229999], dtype=int64)

In [20]:
y_test

array([ 465000, 1580000,  150000, 4950000,  125000,  220000,  450000,
        190000,  740000,  300000,  200000,  775000,  625000,  250000,
        200000,  670000,  400000,  400000,  163000,  630000,   69000,
        450000,  450000,  240000,  355000,  440000,  515000,  600000,
        600000,  220000,  400000,  265000, 1050000, 1200000,  180000,
        180000,   73000,  120000,  225000,  550000,   80000,  495000,
        425000, 2000000,  600000,  170000,   75000,  110000,  725000,
        280000,  140000,  400000,  625000, 1050000,  520000,  285000,
       4950000,  240000,  600000,  300000,  300000,   75000,  368000,
        575000,  486000,  585000,  250000,  250000, 1025000,  520000,
         55000,  200000,  275000,  700000,  350000,  500000,  600000,
        550000,  450000,  190000,  310000,  260000,  620000,  300000,
        175000, 2500000,  625000,  409999, 1200000,  310000, 1295000,
        150000,  390000,  550000,  260000,  320000,  425000,  100000,
        400000,  350

In [22]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [23]:
x_test

array([[-0.55754892, -0.28721955,  0.15477133, ..., -1.68552449,
        -2.88675135, -0.63141381],
       [-1.84514294, -0.05113378,  0.53515785, ..., -1.68552449,
        -2.88675135, -0.63141381],
       [ 0.41864999,  0.18495198,  1.34703116, ...,  0.47234462,
         0.34641016,  2.67019576],
       ...,
       [ 0.09984073, -0.05113378, -0.51550173, ...,  0.47234462,
         0.34641016,  2.67019576],
       [ 0.34945108, -1.9398199 , -0.08568644, ...,  0.47234462,
         0.34641016,  2.67019576],
       [ 0.80665817,  1.12929504, -1.27961778, ..., -1.68552449,
        -2.88675135, -0.63141381]])

In [24]:
x_train

array([[-1.72086037,  0.46123642,  2.26529605, ...,  0.44214019,
         0.33747824, -0.67355278],
       [ 1.67152308, -0.25198189,  2.16054478, ...,  0.44214019,
         0.33747824, -0.67355278],
       [ 0.36772456, -1.67841851,  0.90352958, ...,  0.44214019,
         0.33747824, -0.67355278],
       ...,
       [-1.59298782,  0.69897586, -0.94009271, ...,  0.44214019,
         0.33747824, -0.67355278],
       [ 1.76680066,  0.46123642,  0.06551945, ...,  0.44214019,
         0.33747824, -0.67355278],
       [ 0.74382029, -0.01424245, -0.10208258, ...,  0.44214019,
         0.33747824,  0.94148538]])

In [21]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
y_pred = regressor.predict(x_test)

In [26]:
y_pred

array([3531671.67675961, 3540289.22465226,  485849.18946909,
       3591607.08817059,  661353.77165547,  527729.93900604,
       3257046.02049877,  561913.48459513, 3557306.01258198,
        587623.75165628,  660725.28317818,  587512.29753478,
       3353200.16494704,  754841.10557759,  476884.68739348,
        525127.4305865 ,  596179.10522729,  720631.51262613,
        459734.11571613,  746352.83450621,  382723.46759165,
        703956.76786472,  720655.17925804,  737854.92430303,
       3426865.95325087, 3364384.77782059,  632931.59674858,
        746352.13801899,  596173.93616364,  578977.55006799,
        579048.76179297,  596084.33027675,  670213.58607611,
        772033.92829547,  519611.23852813,  766085.77675559,
        561853.30158595,  493453.24423872,  485368.31584614,
        686941.60707942,  485480.69937071,  783157.971164  ,
        774502.80672671, 3494841.58280786,  570492.83170709,
        544808.64890271,  442602.44456519,  553361.66692065,
        703963.73524524,

In [27]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3531671.68  465000.  ]
 [3540289.22 1580000.  ]
 [ 485849.19  150000.  ]
 ...
 [ 477313.24  210000.  ]
 [ 408872.65   60000.  ]
 [3582925.47 3800000.  ]]
